### ISSUE TITLE
UI bug with server channels with description

### ISSUE THREAD

**Issue by MarcAnt01** [UWPCommunity/Quarrel#107]
Channels with no description are fine
![image](https://user-images.githubusercontent.com/43090263/71513446-abc35000-289a-11ea-8307-104343508519.png)

**Comment by MarcAnt01** [comment]
I have seen that in the latest build that doesn't seem to happen, anyway to check the description I have to use the three dots menu. I'd rather have it visible in that screen

**Comment by Avid29** [comment]
Yes, the description has been moved to be guaranteed in the overflow area. It also only shows the first line. A SubPage will be added with the full description upon tapping the channel name.

This is because the description was causing many bugs with the CommandBar height. All of this is going way beyond the intended use of the CommandBar Content and the Control is fighting back
