### ISSUE TITLE
App is spazzing out

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quarrel#207]
Also, There needs to be server folder support and clicking on a server should open the first channel in the list

**Comment by Avid29** [comment]
Here's a link to download the Insider version: https://www.microsoft.com/store/apps/9NN1ZFD5G6DL
A full rewrite is coming out in a month. The current insider build does not have server folders, however the most recent commit on the rewrite branch does. This issue is for the old Quarrel so I'm going to close it
