### ISSUE TITLE
Ability to upload Xbox captures

### ISSUE THREAD

**Issue by betabites** [UWPCommunity/Quarrel#477]
Although I'm not entirely sure if Xbox allows you to do this, on the Xbox edition I'd love to see the ability to upload my captures from games. This would be absolutely wonderful.

**Comment by Waddle-Doo** [comment]
Xbox captures can be shared by uploading them to Onedrive and sharing them, or by capturing them to an external storage device. Because of the way internally captured game clips are tied to Microsoft's servers, this isn't something that can be worked on unless Xbox has an API that allows downloading of captures from their servers.

**Comment by betabites** [comment]
That's a real shame. It'd be awesome if they created an API for it. Or if they allowed developers to add their app to the capture 'share to' menu.
