### ISSUE TITLE
0 Notifications on discord mobile 

### ISSUE THREAD

**Issue by Junkaat** [UWPCommunity/Quarrel#526]
I've went through all of the troubleshooting options to figure out what's wrong with this I have had this problem since I logged into quarrel, and have found it its not the I need some desperate help with this is there any way you can like take delete my account from your system or give me some troubleshooting options? My notifications only don't work on accounts that haven't been logged in to quarrel.

**Comment by Lumilias** [comment]
I have the same issue.  I've been working with Discord for the past two months trying to fix my account since this happened.  I regret ever downloading Quarrel as a result.

**Comment by augustinpasq** [comment]
Same thing for me. Since my first connection with Quarrel, I no longer have DM notifications, friend requests, or mobile calls. Everything works fine on PC and browser. My client notifications and synchronization settings are correct. If I go into a private conversation on my phone, there is no new message indicator, it is as if the messages were already read on another device.
